apiVersion: v1
kind: Service
metadata:
  name: inji-verify-service
  namespace: tender-portal
spec:
  type: ExternalName
  externalName: inji-verify.default.svc.cluster.local
  ports:
  - port: 80
    targetPort: 80
